### ISSUE TITLE
can not connect peer

### ISSUE THREAD

**Issue by blocknodehub** [MXCzkEVM/simple-mxc-node#15]
WARN [10-21|23:36:34.774] Snapshot extension registration failed   peer=05180ebe err="peer connected on snap without compatible eth support"
INFO [10-21|23:36:43.015] Looking for peers                        peercount=1 tried=149 static=0
INFO [10-21|23:37:03.053] Looking for peers                        peercount=1 tried=99  static=0
WARN [10-21|23:37:13.620] Snapshot extension registration failed   peer=182c008a err="peer connected on snap without compatible eth support"
INFO [10-21|23:37:43.344] Looking for peers                        peercount=0 tried=89  static=0
INFO [10-21|23:37:53.347] Looking for peers                        peercount=2 tried=74  static=0
INFO [10-21|23:38:13.358] Looking for peers                        peercount=2 tried=110 static=0
INFO [10-21|23:38:23.727] Looking for peers                        peercount=2 tried=63  static=0
WARN [10-21|23:38:30.809] Snapshot extension registration failed   peer=05180ebe err="peer connected on snap without compatible eth support"
INFO [10-21|23:38:33.840] Looking for peers                        peercount=2 tried=90  static=0
WARN [10-21|23:38:42.886] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
INFO [10-21|23:38:43.900] Looking for peers                        peercount=1 tried=123 static=0
INFO [10-21|23:39:03.914] Looking for peers                        peercount=2 tried=158 static=0
INFO [10-21|23:39:23.985] Looking for peers                        peercount=1 tried=37  static=0
INFO [10-21|23:39:34.024] Looking for peers                        peercount=2 tried=44  static=0
INFO [10-21|23:39:44.030] Looking for peers                        peercount=1 tried=70  static=0
INFO [10-21|23:39:54.036] Looking for peers                        peercount=2 tried=111 static=0

/usr/local/bin/geth --mxc --networkid=18686 --syncmode=full --gcmode=archive --datadir=/data/mxc-geth --metrics --metrics.expensive --metrics.addr=0.0.0.0 --authrpc.addr=0.0.0.0 --authrpc.vhosts=* --http --http.api=debug,eth,net,web3,txpool,mxc --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --ws --ws.api=debug,eth,net,web3,txpool,mxc --ws.addr=0.0.0.0 --ws.origins=* --rpc.txfeecap=0 --bootnodes=enode://d226b47b9c1199a21d9d11d664269261717b1c67fa67062d3eecc84285537fe161cbac3804ea036ed516d257f95215f49400952f03c43174d3a3af415ff47d75@207.246.101.30:30303,enode://1f5e524a11f5dc02f03113faa4090cafa0d692e9decff1199a1dc304d2d1f6fba07a7e7016026e0356b3e6c35e873a95a295c0326e888554224a1ec3fded330a@149.28.212.112:30303

**Comment by sheenhx** [comment]
you will need to provide error logs from geth, thanks!

**Comment by blocknodehub** [comment]
> you will need to provide error logs from geth, thanks!

There is no more detailed information, geth process does not synchronize data, does not need genesis.json initialization data, but I do not find it in the documentation

**Comment by sheenhx** [comment]
``docker compose restart``
This will start to sync the data, if you have more questions let me know!
