### ISSUE TITLE
Data synchronization on the node is incorrect

### ISSUE THREAD

**Issue by blocknodehub** [MXCzkEVM/simple-mxc-node#17]
Why does my node synchronize the block (0x38bee "hash": "0 x25808530c0eff7aa3c0eccb3f8e616bf48ff93ec405067fb7d79612f2aff9f9b") and https://rpc.mxc.com (0 x38bee "hash" : "0 xe0d61b8519468fd3f88bd2ecf13c4e25e3b35704ceebf2f563a5f531c66a0e79") is always inconsistent, resynchronize cannot solve. But the other blocks are the same

**Comment by sheenhx** [comment]
you need to run mxc client with mxc geth, let me know if this solves the problem

**Comment by blocknodehub** [comment]
> you need to run mxc client with mxc geth, let me know if this solves the problem also .env should be configured according to what we instructed in this repo, what is your L1 node provider URL ?

https://github.com/MXCzkEVM/simple-mxc-node/issues/19#issue-2109457633
