### ISSUE TITLE
The node always synchronizes the wrong data

### ISSUE THREAD

**Issue by blocknodehub** [MXCzkEVM/simple-mxc-node#19]
Since the 141nd block, the node has synchronized the wrong data, which looks like it ran into the fork chain, but the obtained chain_id(18686) is correct. The data before block 141 was also correct. No matter which version is used, or the data is resynchronized, there is always a synchronization error starting from block 141

**Comment by sheenhx** [comment]
docker compose restart mxc_client_driver
Could solve it
Make sure your L1 endpoint is a good arb RPC like quicknode 
So you can continue to sync
